name: nae
description: Nae project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.7+9

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  intl: ^0.17.0
  uuid: ^3.0.7
  confirm_dialog: ^1.0.1
  flutter_spinkit: ^5.1.0
  select_dialog: ^2.0.0
  flutter_multi_formatter: ^2.10.2
  permission_handler: ^10.2.0
  data_table_2: ^2.3.12
  prompt_dialog: ^1.0.9
  timeago: ^3.3.0
  country_icons: ^2.0.2

  #flutter_feathersjs: ^4.0.5+1
  flutter_feathersjs:
    git: https://github.com/DigitaIAM/flutter_feathersjs.dart
    #path: ../flutter_feathersjs.dart
  http: ^0.13.5
  mime: ^1.0.4
  http_parser: ^4.0.2

  #flutter_redux: ^0.10.0
  #get_it: ^7.2.0

  #copy_with_extension_gen: ^5.0.0
  bloc_concurrency: ^0.2.1
  flutter_bloc: ^8.1.2
  stream_transform: ^2.1.0

  loading_indicator: ^3.1.0

  upgrader: ^6.2.0
  flutter_styled_toast: ^2.1.3
  flutter_screenutil: ^5.6.1
  overflow_view: ^0.3.1
  adaptive_breakpoints: ^0.1.6
  #dual_screen: ^1.0.3
  side_navigation: ^1.0.4
  pluto_grid: ^5.4.9
  grouped_list: ^5.1.2
  dropdown_search: ^5.0.5
  #reactive_forms: ^14.2.0
  flutter_form_builder: ^7.7.0
  #form_builder_extra_fields: ^8.3.0
  #flutter_chips_input: # workaround for https://github.com/danvick/flutter_chips_input/issues/136
  #  git: https://github.com/bradintheusa/flutter_chips_input
  form_builder_validators: ^8.4.0
  equatable: ^2.0.5
  #flutter_wall_layout: ^2.1.1
  #docking: ^1.5.0
  #xml_layout: ^2.3.15

  image: ^4.0.13
  #flutter_pos_printer_platform: ^1.0.12
  #esc_pos_printer: ^4.1.0
  #esc_pos_utils: ^1.1.0
  windows1251: ^1.0.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/en.json
    - lang/ru.json
    - lang/uz.json
    - lang/tj.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
